import { GetServerSidePropsContext } from 'next';
import Head from 'next/head'
import Image from "next/image"

import { Header } from "@/components/header";
import { TopBar } from "@/components/topbar";
import { Homeherocategories } from '@/components/homeherocategories';
import { Advantageitem } from '@/components/advantageitem';
import { Advantagesection } from '@/components/advantagesection';

import { Categories } from '@/models/categories';

import { AspectRatio, Box, Button, Container, Flex, FormControl, FormHelperText, FormLabel, Grid, GridItem, Heading, Input, SimpleGrid, Text } from '@chakra-ui/react';
import { StarIcon } from '@chakra-ui/icons';
import { Productcard } from '@/components/productcard';
import { start } from 'repl';
import { group } from 'console';
import { GroupedProducts, groupProductsByCategory } from '@/util/groupProductsByCategory';
import { Homeproductsgrid } from '@/components/homeproductsgrid';

import bannerNewSeason from "/public/banner-new-season.jpg";
import bannerSale from "/public/banner-sale.jpg";
import { CenteredLabel } from '@/components/centeredlabel';
import { Promobanner } from '@/components/promobanner';

export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
}

type Props = {
  products: Product[],
  categories: Categories[],
  productsGroupByCategory: GroupedProducts[],
}





export default function Home({ products, categories, productsGroupByCategory }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Box marginBottom="32px">
        <Header />
      </Box>

      <main>
        <Container>
          <Homeherocategories categories={categories}></Homeherocategories>

          <Advantagesection />

        </Container>

        <Container maxW={{
          base: "100%",
          md: "1110px"
        }}
          paddingX="0">

          {Object.entries(productsGroupByCategory).map(([category, products]) => {
            return (
              <Box key={category} marginBottom="64px">
                <Heading as="h2"
                  size="lg"
                  textTransform="uppercase"
                  margin={{
                    base: "0 0 16px 16px",
                    md: "0 0 24px"

                  }}>
                  {category}
                </Heading>
                <Homeproductsgrid products={products} />
              </Box>
            );
          })
          }
        </Container>

        <Container>
          <SimpleGrid
            minChildWidth="255px"
            spacing={{
              base: "16px",
              md: "32px"
            }}>

            <Promobanner image={bannerNewSeason}>
              <Text fontSize="sm" color="gray.500">
                New season
              </Text>
              <Text fontSize="lg" fontWeight="bold" whiteSpace="nowrap">
                Lookbook collection
              </Text>
            </Promobanner>

            <Promobanner image={bannerSale}>
              <Text fontSize="sm" color="gray.500">
                Sale
              </Text>
              <Text fontSize="lg" fontWeight="bold" whiteSpace="nowrap">
                Get up to {""}
                <Text as="span" color="red">
                  50% off
                </Text>
              </Text>
            </Promobanner>

          </SimpleGrid>
        </Container>

        <Container background={"linear-gradient(180deg, #f3f2f2 0%, #dcdbdb 100%);"} margin="32px auto" padding="24px" maxW={"100%"}>
          <Box maxW={"532px"} margin="auto" gap="32px" as="article" bgColor="white" padding="32px" > 
          <Grid gap="32px" maxW="352px" margin="auto"  textAlign="center">
            <header>
            <Heading size="sm" textTransform="uppercase" color="gray">Special offer </Heading>
            <Heading size="2xl" textTransform="uppercase">Subscribe and {" "} <Text as="span" color="red"> get 10% off</Text>
            </Heading>
            </header>
            <Grid as="form" action="" gap="24px">
              <FormControl>
                <Input height="64px" textAlign="inherit" borderRadius="0" type='email' placeholder="Enter your email" backgroundColor="gray.100"/>
              </FormControl>
              <Button bgColor={"black"} width="100%" size="lg">Subscribe</Button>
            </Grid>
          </Grid>
          </Box>
        </Container>
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())
  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res => res.json())

  const productsGroupByCategory = groupProductsByCategory(products);

  return {
    props: {
      products,
      categories,
      productsGroupByCategory,
    }
  }
}
