import { GetServerSidePropsContext } from 'next';
import Head from 'next/head'
import Image from "next/image"

import { Header } from "@/components/header";
import { TopBar } from "@/components/topbar";
import { Homeherocategories } from '@/components/homeherocategories';
import { Advantageitem } from '@/components/advantageitem';
import { Advantagesection } from '@/components/advantagesection';

import { Categories } from '@/models/categories';

import { AspectRatio, Box, Container, Flex, Grid, GridItem, SimpleGrid, Text } from '@chakra-ui/react';
import { StarIcon } from '@chakra-ui/icons';
import { Productcard } from '@/components/productcard';


export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
}

type Props = {
  products: Product[],
  categories: Categories[]
}

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Box marginBottom="32px">
        <Header />
      </Box>

      <main>
        <Container size={{
          lg: "lg"
        }}>
          <Homeherocategories categories={categories}></Homeherocategories>

          <Advantagesection />

          <SimpleGrid minChildWidth='255px' spacing='30px'>  
          {products.map(product => {
            return <Productcard {...product} key={product.id}/>
          })}
        </SimpleGrid>

        </Container>

      
      </main>
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json())
  const categories = await fetch('https://fakestoreapi.com/products/categories')
    .then(res => res.json())

  return {
    props: {
      products,
      categories
    }
  }
}
